version: '3.9'
services:
  postgres-db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: pluaj
      POSTGRES_PASSWORD: Pichincha1
      POSTGRES_DB: dbUsuario
    ports:
      - "5432:5432"
    networks:
      - spring-net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pluaj"]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: springboot-rest-postgres:v1.0.0
    container_name: springboot-app
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/dbUsuario
      SPRING_DATASOURCE_USERNAME: pluaj
      SPRING_DATASOURCE_PASSWORD: Pichincha1
      SERVER_PORT: 9082
    ports:
      - "9082:9082"
    networks:
      - spring-net

networks:
  spring-net:

volumes:
  postgres_data: